# docker-compose.yml

version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend-playground
    ports:
      - '5432:5432'
    volumes:
      - api-db:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      - DATABASE_PASSWORD=password
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=backend-playground
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - API_HOST=0.0.0.0
      - API_PORT=3000
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  api-db:
